# Configuration for Doclings - All config and secrets in one file
{{- $namespace := .Values.namespace | default .Release.Namespace -}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "doclings.fullname" . }}-config
  namespace: {{ $namespace }}
  labels:
    {{- include "doclings.labels" . | nindent 4 }}
data:
  DOCLING_SERVE_ENABLE_UI: {{ .Values.config.enableUI | quote }}
  {{- range $key, $value := .Values.config.extraEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

---
{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "doclings.fullname" . }}-storage
  namespace: {{ $namespace }}
  labels:
    {{- include "doclings.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "doclings.labels" -}}
helm.sh/chart: {{ include "doclings.chart" . }}
{{ include "doclings.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "doclings.selectorLabels" -}}
app.kubernetes.io/name: {{ include "doclings.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "doclings.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "doclings.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "doclings.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "doclings.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

{{/*
Expand the name of the chart.
*/}}
{{- define "doclings.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}
